"""phase 1 fixation schema

Revision ID: a2f36c3147d2
Revises: 
Create Date: 2026-04-30 13:52:30.716342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f36c3147d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('actual_capitalizations',
    sa.Column('capitalization_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('capitalization_date', sa.Date(), nullable=False),
    sa.Column('source_label', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_actual_caps_amount_non_negative'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('capitalization_id')
    )
    op.create_table('client_profiles',
    sa.Column('client_profile_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('client_profile_id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('employment_records',
    sa.Column('employment_record_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('employer_name', sa.String(length=255), nullable=False),
    sa.Column('work_start_date', sa.Date(), nullable=False),
    sa.Column('work_end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('work_end_date IS NULL OR work_end_date >= work_start_date', name='ck_employment_dates_order'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('employment_record_id')
    )
    op.create_table('fixation_runs',
    sa.Column('fixation_run_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('calculation_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('source_data_version_label', sa.String(length=128), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('success', 'validation_failed')", name='ck_fixation_runs_status'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('fixation_run_id')
    )
    op.create_table('fixation_audit_rows',
    sa.Column('fixation_audit_row_id', sa.String(length=64), nullable=False),
    sa.Column('fixation_run_id', sa.String(length=64), nullable=False),
    sa.Column('row_order', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('input_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('output_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('impact_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('details_payload', sa.JSON(), nullable=False),
    sa.CheckConstraint('impact_amount >= 0', name='ck_fixation_audit_rows_impact_non_negative'),
    sa.ForeignKeyConstraint(['fixation_run_id'], ['fixation_runs.fixation_run_id'], ),
    sa.PrimaryKeyConstraint('fixation_audit_row_id'),
    sa.UniqueConstraint('fixation_run_id', 'row_order', name='uq_fixation_audit_rows_run_order')
    )
    op.create_table('fixation_input_snapshots',
    sa.Column('fixation_input_snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('fixation_run_id', sa.String(length=64), nullable=False),
    sa.Column('input_contract_version', sa.String(length=64), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fixation_run_id'], ['fixation_runs.fixation_run_id'], ),
    sa.PrimaryKeyConstraint('fixation_input_snapshot_id'),
    sa.UniqueConstraint('fixation_run_id')
    )
    op.create_table('fixation_results',
    sa.Column('fixation_result_id', sa.String(length=64), nullable=False),
    sa.Column('fixation_run_id', sa.String(length=64), nullable=False),
    sa.Column('result_contract_version', sa.String(length=64), nullable=False),
    sa.Column('initial_exempt_capital', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('grant_impact_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('future_grant_reserved', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('future_grant_impact', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('actual_capitalization_impact', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('idf_impact', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_impact', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('remaining_exempt_capital', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_exempt_pension', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('capital_exemption_percentage', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('pension_exemption_percentage', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('result_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('initial_exempt_capital >= 0 AND grant_impact_total >= 0 AND future_grant_reserved >= 0 AND future_grant_impact >= 0 AND actual_capitalization_impact >= 0 AND idf_impact >= 0 AND total_impact >= 0 AND remaining_exempt_capital >= 0 AND monthly_exempt_pension >= 0', name='ck_fixation_results_non_negative_money'),
    sa.ForeignKeyConstraint(['fixation_run_id'], ['fixation_runs.fixation_run_id'], ),
    sa.PrimaryKeyConstraint('fixation_result_id'),
    sa.UniqueConstraint('fixation_run_id')
    )
    op.create_table('fixation_validation_errors',
    sa.Column('fixation_validation_error_id', sa.String(length=64), nullable=False),
    sa.Column('fixation_run_id', sa.String(length=64), nullable=False),
    sa.Column('error_order', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.CheckConstraint("severity = 'error'", name='ck_fixation_validation_errors_severity'),
    sa.ForeignKeyConstraint(['fixation_run_id'], ['fixation_runs.fixation_run_id'], ),
    sa.PrimaryKeyConstraint('fixation_validation_error_id'),
    sa.UniqueConstraint('fixation_run_id', 'error_order', name='uq_fixation_validation_errors_run_order')
    )
    op.create_table('grants',
    sa.Column('grant_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('employment_record_id', sa.String(length=64), nullable=True),
    sa.Column('employer_name', sa.String(length=255), nullable=True),
    sa.Column('nominal_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('indexed_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('grant_date', sa.Date(), nullable=False),
    sa.Column('work_start_date', sa.Date(), nullable=False),
    sa.Column('work_end_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('indexed_amount >= 0', name='ck_grants_indexed_amount_non_negative'),
    sa.CheckConstraint('nominal_amount IS NULL OR nominal_amount >= 0', name='ck_grants_nominal_amount_non_negative'),
    sa.CheckConstraint('work_end_date >= work_start_date', name='ck_grants_work_dates_order'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['employment_record_id'], ['employment_records.employment_record_id'], ),
    sa.PrimaryKeyConstraint('grant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grants')
    op.drop_table('fixation_validation_errors')
    op.drop_table('fixation_results')
    op.drop_table('fixation_input_snapshots')
    op.drop_table('fixation_audit_rows')
    op.drop_table('fixation_runs')
    op.drop_table('employment_records')
    op.drop_table('client_profiles')
    op.drop_table('actual_capitalizations')
    op.drop_table('clients')
    # ### end Alembic commands ###
